type conversion fixed for decimal and bigint
doctrine/doctrine-laminas-hydrator pull request #24
Opened 2021-02-06 15:48 UTC by lampi87

Hello everyone,

I found a bug in the type conversion for decimal. It's casted as string instead float.
With this fix it is possible to use strict types in php 7.4

Best regards

2021-03-23 20:44 UTC, lampi87 commented
Hi!

Any comments or suggestions regarding this fix?

Best regards

2021-03-28 00:17 UTC, TomHAnderson commented
I've always disliked that portion of code you've put your fix in.  I think it is an appropriate fix and requires a minor version change.

2021-03-28 00:19 UTC, TomHAnderson commented
Actually, I think now that this will require a major version number because we're changing data types.  Would love to hear your view on this versioning issue then I'll get it merged asap.

2021-03-28 05:22 UTC, lampi87 commented
I'm not sure about a major version change. In my point of view it's "just" a bugfix for strict types in php7.4 and above.
But at the end it's your decision.

2021-03-28 07:15 UTC, beberlei requested changes
These changes are flawed, the current behavior is correct.

Use the `float` type to get casted to `float`.

2021-03-28 07:15 UTC, beberlei commented on src/DoctrineObject.php
> +            case 'bigint':
bigints must always be cast to string, because their value range exceeds PHPs range that can represent integers.

2021-03-28 07:15 UTC, beberlei commented on src/DoctrineObject.php
> +                $value = (float) $value;
a Decimal is not a float, floats loose precision, decimals don't

2021-10-15 11:33 UTC, driehle commented
Thank you for your time and contribution @lampi87. However, as beberlei pointed out, the current behaviour is correct. A `bigint` must be casted to `string`, as bigint exceed PHP's int range. A `decimal` must be casted to `string` as well, as floats loose precision, while decimals don't.

2021-10-15 11:33 UTC, closed without merging