add support for datetime_immutable and datetimetz_immutable
doctrine/doctrine-laminas-hydrator pull request #30
Opened 2021-10-02 16:37 UTC by HeyRatFans

This PR adds support for the doctrine `datetime_immutable `and `datetimetz_immutable` types.

2021-10-06 00:10 UTC, TomHAnderson approved these changes

2021-10-07 14:48 UTC, driehle requested changes
I am not sure about the changes, they may result in a `DateTimeImmutable` object in a `datetime` field and vice versa. See my suggestions for how this could be solved.

2021-10-07 14:48 UTC, driehle commented on test/DoctrineObjectTest.php
> +            ->expects($this->any())
```suggestion
```

Not needed.

2021-10-07 14:48 UTC, driehle commented on test/DoctrineObjectTest.php
> +            ->expects($this->any())
```suggestion
```

2021-10-07 14:48 UTC, driehle commented on test/DoctrineObjectTest.php
> +            ->expects($this->any())
```suggestion
```

2021-10-07 14:48 UTC, driehle commented on test/DoctrineObjectTest.php
> +                    function ($arg) {
```suggestion
                    function (string $arg): string {
```

2021-10-07 14:48 UTC, driehle commented on test/DoctrineObjectTest.php
> +            ->expects($this->any())
```suggestion
```

2021-10-07 14:48 UTC, driehle commented on test/DoctrineObjectTest.php
> +            ->expects($this->any())
```suggestion
```

2021-10-07 14:48 UTC, driehle commented on test/DoctrineObjectTest.php
> +            ->expects($this->any())
```suggestion
```

2021-10-07 14:48 UTC, driehle commented on src/DoctrineObject.php
> +                $isImmutable = substr($typeOfField, -9) === 'immutable';
```suggestion
                $isImmutable = substr($typeOfField, -9) === 'immutable';
                if (
                    ($isImmutable && $value instanceof DateTimeImmutable)
                    || (!$isImmutable && $value instanceof DateTime)
                ) {
                    return $value;
                } elseif ($isImmutable && $value instanceof DateTime) {
                    return DateTimeImmutable::createFromMutable($value);
                } elseif ($!isImmutable && $value instanceof DateTimeImmutable) {
                    return DateTime::createFromImmutable($value);
                }
```

I think this part needs to be more explicit, since for immutable fields the function should only DateTimeImmutable should be returned and for non-immutable fields only DateTime should be returned. Simply checking for DateTimeInterface will not guarantee this.

2021-10-07 14:48 UTC, driehle commented on src/DoctrineObject.php
> +use DateTimeInterface;
```suggestion
```

2021-10-08 21:49 UTC, HeyRatFans commented on src/DoctrineObject.php
> +                $isImmutable = substr($typeOfField, -9) === 'immutable';
DateTime::createFromImmutable is only available since PHP 7.3 - project is still targeting 7.2.

An alternative might be

`return new DateTime($value->format(DateTimeInterface::ISO8601));`

Thoughts?

2021-10-09 07:17 UTC, driehle commented on src/DoctrineObject.php
> +                $isImmutable = substr($typeOfField, -9) === 'immutable';
I think for 2.2.0 we should rather drop 7.2 anyways, as it is EOL for almost one year now. Dropping 7.2 is already pending in #29. Dropping PHP versions is usually considered minor changes and so are new features, so both could/must go in a new minor release anyways.

2021-10-09 16:35 UTC, HeyRatFans commented
Changes made as suggested by @driehle. For targeting 2.2.x, I'm assuming someone will create such a branch.

2021-10-09 17:03 UTC, driehle commented
@TomHAnderson Could you please create a 2.2.x branch?

2021-10-09 22:03 UTC, TomHAnderson commented
@driehle done:  https://github.com/doctrine/doctrine-laminas-hydrator/tree/2.2.x

2021-10-09 22:03 UTC, TomHAnderson commented
I've changed the base on this PR to 2.2.x

2021-10-15 13:56 UTC, driehle commented
@HeyRatFans Could you please fix the two coding standard issues that were raised by Github actions?

Further, your code added to `DoctrineObjectTest.php` doesn't do anything. Your method `configureObjectManagerForSimpleEntityWithDateTimeImmutable()` sets up an object manager that is not used anywhere. Besides, the type conversions are all tested in a separate file, see `DoctrineObjectTypeConversionsTest.php`.

Could you please undo your changes in `DoctrineObjectTest.php` and in `DoctrineObjectTypeConversionsTest.php` copy the methods `testHandleTypeConversionsDatetime()` and `testHandleTypeConversionsDatetimez()` to respective variants using `DateTimeImmutable`? For mocking the object manager you can use `$this->configureObjectManagerForSimpleEntityWithGenericField('datetime_immutable');`, i.e. no need to create an entity asset.

2021-10-17 11:30 UTC, driehle commented
I added test cases, but there is still a Psalm issue. I will look into this.

2021-10-17 11:48 UTC, driehle approved these changes

2021-10-17 11:48 UTC, driehle commented
@greg0ire Do you agree with 749f918 or is there a better solution?

2021-10-17 12:48 UTC, merged

2021-10-18 08:19 UTC, driehle commented
2.2.0 has been [released](https://github.com/doctrine/doctrine-laminas-hydrator/releases/tag/2.2.0)