Prepare docs for Doctrine website
doctrine/doctrine-laminas-hydrator pull request #34
Opened 2021-10-18 21:39 UTC by driehle

Similar to doctrine/DoctrineModule#733, this PR prepares the docs for being rendered on the Doctrine website. The README has been split into multiple sections and converted from .md to .rst. A .doctrine-project.json is added.

Similar to and in line with:

- https://github.com/doctrine/DoctrineModule/pull/733
- https://github.com/doctrine/DoctrineORMModule/pull/672
- https://github.com/doctrine/DoctrineMongoODMModule/pull/230

2021-10-20 21:06 UTC, SenseException requested changes

2021-10-20 21:06 UTC, SenseException commented on docs/en/basic-usage.rst
> +   Note: internally, for a given collection, if an array contains
```suggestion
.. note::

   internally, for a given collection, if an array contains
```

2021-10-20 21:06 UTC, SenseException commented on docs/en/performance-considerations.rst
> +..
Not sure why those are used here while not in the `If you are not comfortable with Fieldsets` paragraph. Did you plan to use a note here?

2021-10-20 21:18 UTC, driehle commented on docs/en/basic-usage.rst
> +   Note: internally, for a given collection, if an array contains
Fixed

2021-10-20 21:18 UTC, driehle commented on docs/en/performance-considerations.rst
> +..
Probably a left-over from the pandoc conversion. I added a note there.

2021-10-20 21:20 UTC, SenseException approved these changes

2021-10-21 01:26 UTC, TomHAnderson approved these changes
I'm going to approve this **for now**.  But there are a number of grammatical errors throughout the docs which should be corrected.  I'm willing to do a PR on the docs as a follow-up to this PR to address them.  I'm more concerned about getting this in place on the website.

Please create an issue, assigned to me, to review the docs' English as a follow-up to approving this PR.

2021-10-21 04:17 UTC, TomHAnderson commented
If you want me to push a PR to this PR before you merge, I'm OK with that.  I'll leave the decision for when to merge up to @driehle

2021-10-21 07:13 UTC, driehle commented
@TomHAnderson I'll merge this for now as this will likely enable me to render `doctrine-website` locally to see if the basic integration is all set up.

2021-10-21 07:13 UTC, merged